connector.name=mongodb
mongodb.connection-url=mongodb://mongodb-node1:27017,mongodb-node2:27017,mongodb-node3:27017
mongodb.credentials=mongodb://username:password@mongodb-node1:27017
mongodb.schema-collection=presto_schemas
mongodb.case-insensitive-name-matching=false

